:- module(words, [word/1]).

word("poder").
word("moral").
word("honra").
word("limpa").
word("fazer").
word("tempo").
word("carro").
word("grato").
word("viver").
word("cheio").
word("verde").
word("saber").
word("lugar").
word("vento").
word("fundo").
word("claro").
word("homem").
word("mulher").
word("praia").
word("sonho").
word("raiva").
word("tempo").
word("amigo").
word("plano").
word("festa").
word("globo").
word("leite").
word("dente").
word("falar").
word("brisa").
word("canto").
word("quase").
word("ponto").
word("campo").
word("salto").
word("barco").
word("noite").
word("linha").
word("raios").
word("tarde").
word("morto").
word("vazio").
word("clima").
word("banco").
word("chave").
